version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: shopli_db
    environment:
      POSTGRES_USER: shopli_user
      POSTGRES_PASSWORD: shopli_password
      POSTGRES_DB: shopli_dev
    ports:
      - "5432:5432"
    volumes:
      - shopli_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  shopli_pg_data:
